# Generated by Django 4.2.7 on 2023-12-14 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_list_detailed_descr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='detailed_descr',
        ),
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AddField(
            model_name='list',
            name='summary',
            field=models.TextField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='list',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.status', verbose_name='Статус'),
        ),
    ]
