# Generated by Django 4.2.7 on 2023-12-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_status_type_remove_list_detailed_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
