# Generated by Django 4.2.7 on 2023-12-14 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_list_created_at_alter_list_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='list',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.type', verbose_name='Тип'),
        ),
    ]
