# Generated by Django 4.2.7 on 2023-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_list_status_alter_list_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='type',
        ),
        migrations.AddField(
            model_name='list',
            name='type',
            field=models.ManyToManyField(related_name='types', to='webapp.type', verbose_name='Тип'),
        ),
    ]
