# Generated by Django 4.2.7 on 2023-12-19 11:11

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_list_type_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, validators=[webapp.models.bad_words], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='list',
            name='summary',
            field=models.CharField(max_length=100, validators=[webapp.models.special_characters, webapp.models.bad_words], verbose_name='Краткое описание'),
        ),
    ]
