# Generated by Django 4.2.7 on 2023-12-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_list_description_alter_list_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.project'),
        ),
    ]
